version: '4'

services:
  api-gateway:
    platform: linux/amd64
    build:
      context: ./Gateway
      target: prod
    restart: unless-stopped
    environment:
      JWT_SECRET: $JWT_SECRET
      JWT_EXPIRES_IN: $JWT_EXPIRES_IN
      JWT_REFRESH_EXPIRES_IN: $JWT_REFRESH_EXPIRES_IN
      PORT: $GATEWAY_PORT
      USERSMS_HOST: $USERSMS_HOST
      USERSMS_PORT: $USERSMS_PORT
    ports:
      - 3000:$GATEWAY_PORT
    networks:
      - microservices-network
      - fileserver-network

  usersms:
    platform: linux/amd64
    build:
      context: ./UsersMS
      target: prod
    hostname: $USERSMS_HOST
    restart: unless-stopped
    environment:
      PORT: $USERSMS_PORT
      HEALTHCHECK_PORT: $USERSMS_HEALTHCHECK_PORT
      DB_HOST: $USERSDB_HOST
      DB_PORT: $USERSDB_PORT
      DB_NAME: $USERSDB_DATABASE
      DB_USER: $USERSDB_USER
      DB_PASSWORD: $USERSDB_PASSWORD
    ports:
      - 3001:$USERSMS_HEALTHCHECK_PORT
    networks:
      - microservices-network
      - usersdb-network
    depends_on:
      - usersdb
  usersdb:
    image: mysql:latest
    platform: linux/amd64
    hostname: $USERSDB_HOST
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $USERSDB_ROOT_PASSWORD
      MYSQL_DATABASE: $USERSDB_DATABASE
      MYSQL_USER: $USERSDB_USER
      MYSQL_PASSWORD: $USERSDB_PASSWORD
    networks:
      - usersdb-network
  adminer:
    image: adminer
    platform: linux/amd64
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - usersdb-network
  fileserver:
    hostname: $FILESERVER_HOST
    platform: linux/amd64
    build: ./FileServer
    ports: 
      - 3456:${FILESERVER_PORT}
    volumes:
      - ./DockerVolume/files:/app/files
    environment:
      PORT: ${FILESERVER_PORT}
      MAX_FILE_SIZE: 100
    networks:
      - fileserver-network
networks:
  microservices-network:
    driver: bridge
  usersdb-network:
    driver: bridge
  fileserver-network:
    driver: bridge