version: '4'

services:
  api-gateway:
    build:
      context: ./Gateway
      target: dev
    restart: unless-stopped
    environment:
      JWT_SECRET: $JWT_SECRET
      JWT_EXPIRES_IN: $JWT_EXPIRES_IN
      JWT_REFRESH_EXPIRES_IN: $JWT_REFRESH_EXPIRES_IN
      PORT: $GATEWAY_PORT
      USERSMS_HOST: $USERSMS_HOST
      USERSMS_PORT: $USERSMS_PORT
      FILESERVER_HOST: $FILESERVER_HOST
      FILESERVER_PORT: $FILESERVER_PORT
    ports:
      - 3000:$GATEWAY_PORT
    volumes:
      - ./Gateway/src:/app/src
    networks:
      - microservices-network-dev
      - fileserver-network-dev

  usersms:
    build:
      context: ./UsersMS
      target: dev
    hostname: $USERSMS_HOST
    restart: unless-stopped
    environment:
      PORT: $USERSMS_PORT
      HEALTHCHECK_PORT: $USERSMS_HEALTHCHECK_PORT
      DB_HOST: $USERSDB_HOST
      DB_PORT: $USERSDB_PORT
      DB_NAME: $USERSDB_DATABASE
      DB_USER: $USERSDB_USER
      DB_PASSWORD: $USERSDB_PASSWORD
    ports:
      - 3001:$USERSMS_HEALTHCHECK_PORT
    volumes:
      - ./UsersMS/src:/app/src
    networks:
      - microservices-network-dev
      - usersdb-network-dev
    depends_on:
      - usersdb

  usersdb:
    image: mysql:latest
    hostname: $USERSDB_HOST
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $USERSDB_ROOT_PASSWORD
      MYSQL_DATABASE: $USERSDB_DATABASE
      MYSQL_USER: $USERSDB_USER
      MYSQL_PASSWORD: $USERSDB_PASSWORD
    networks:
      - usersdb-network-dev

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
    networks:
      - usersdb-network-dev

  fileserver:
    build: ./FileServer
    hostname: $FILESERVER_HOST
    restart: unless-stopped
    ports: 
      - 3456:${FILESERVER_PORT}
    volumes:
      - ./DockerVolume/files:/app/files
    environment:
      PORT: ${FILESERVER_PORT}
      MAX_FILE_SIZE: 100
    networks:
      - fileserver-network-dev

networks:
  microservices-network-dev:
    driver: bridge
  usersdb-network-dev:
    driver: bridge
  fileserver-network-dev:
    driver: bridge