version: '4'

services:
  api-gateway:
    platform: linux/amd64
    build:
      context: ./Gateway
      target: prod
    restart: unless-stopped
    environment:
      JWT_SECRET: $JWT_SECRET
      JWT_EXPIRES_IN: $JWT_EXPIRES_IN
      JWT_REFRESH_EXPIRES_IN: $JWT_REFRESH_EXPIRES_IN
      PORT: $GATEWAY_PORT
      USERSMS_HOST: $USERSMS_HOST
      USERSMS_PORT: $USERSMS_PORT
      FILESERVER_HOST: $FILESERVER_HOST
      FILESERVER_PORT: $FILESERVER_PORT
      USERINFOMS_HOST: $USERINFOMS_HOST
      USERINFOMS_PORT: $USERINFOMS_PORT
    ports:
      - $GATEWAY_PORT
    networks:
      - microservices-networks
      - fileserver-networks

  users-ms:
    platform: linux/amd64
    build:
      context: ./UsersMS
      target: prod
    hostname: $USERSMS_HOST
    restart: unless-stopped
    environment:
      PORT: $USERSMS_PORT
      HEALTHCHECK_PORT: $USERSMS_HEALTHCHECK_PORT
      DB_HOST: $USERSDB_HOST
      DB_PORT: $USERSDB_PORT
      DB_NAME: $USERSDB_DATABASE
      DB_USER: $USERSDB_USER
      DB_PASSWORD: $USERSDB_PASSWORD
    ports:
      - $USERSMS_HEALTHCHECK_PORT:$USERSMS_HEALTHCHECK_PORT
    networks:
      - microservices-networks
      - users-db-networks
    depends_on:
      - users-db

  users-db:
    image: mysql:latest
    hostname: $USERSDB_HOST
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $USERSDB_ROOT_PASSWORD
      MYSQL_DATABASE: $USERSDB_DATABASE
      MYSQL_USER: $USERSDB_USER
      MYSQL_PASSWORD: $USERSDB_PASSWORD
    volumes:
      - ./DockerVolume/users-db:/var/lib/mysql
    networks:
      - users-db-networks

  userinfo-ms:
    platform: linux/amd64
    build:
      context: ./UserInfoMS
      target: prod
    hostname: $USERINFOMS_HOST
    restart: unless-stopped
    environment:
      PORT: $USERINFOMS_PORT
      HEALTHCHECK_PORT: $USERINFOMS_HEALTHCHECK_PORT
      DB_HOST: $USERINFODB_HOST
      DB_PORT: $USERINFODB_PORT
      DB_NAME: $USERINFODB_DATABASE
      DB_USER: $USERINFODB_USER
      DB_PASSWORD: $USERINFODB_PASSWORD
    ports:
      - $USERINFOMS_HEALTHCHECK_PORT:$USERINFOMS_HEALTHCHECK_PORT
    networks:
      - microservices-networks
      - userinfo-db-networks
    depends_on:
      - userinfo-db


  userinfo-db:
    image: mysql:latest
    hostname: $USERINFODB_HOST
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: $USERINFODB_ROOT_PASSWORD
      MYSQL_DATABASE: $USERINFODB_DATABASE
      MYSQL_USER: $USERINFODB_USER
      MYSQL_PASSWORD: $USERINFODB_PASSWORD
    # volumes:
    #   - ./DockerVolume/userinfo-db:/var/lib/mysql
    networks:
      - userinfo-db-networks

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080
    networks:
      - users-db-networks
      - userinfo-db-networks

  fileserver:
    build: ./FileServer
    hostname: $FILESERVER_HOST
    restart: unless-stopped
    ports: 
      - ${FILESERVER_PORT}:${FILESERVER_PORT}
    volumes:
      - ./DockerVolume/files:/app/files
    environment:
      PORT: ${FILESERVER_PORT}
      MAX_FILE_SIZE: 100
    networks:
      - fileserver-networks

networks:
  microservices-networks:
    driver: bridge
  users-db-networks:
    driver: bridge
  userinfo-db-networks:
    driver: bridge
  fileserver-networks:
    driver: bridge