version: '4'

services:
  api-gateway:
    build:
      context: ./Gateway
      target: dev
    restart: unless-stopped
    environment:
      PORT: $GATEWAY_PORT
      USERSMS_HOST: $USERSMS_HOST
      USERSMS_PORT: $USERSMS_PORT
    ports:
      - $GATEWAY_PORT:$GATEWAY_PORT
    volumes:
      - ./Gateway/src:/app/src
    networks:
      - microservices-network-dev

  usersms:
    build:
      context: ./UsersMS
      target: dev
    hostname: $USERSMS_HOST
    restart: unless-stopped
    environment:
      PORT: $USERSMS_PORT
    volumes:
      - ./UsersMS/src:/app/src
    networks:
      - microservices-network-dev

networks:
  microservices-network-dev:
    driver: bridge