version: '4'

services:
  api-gateway:
    platform: linux/amd64
    build:
      context: ./Gateway
      target: prod
    restart: unless-stopped
    environment:
      PORT: $GATEWAY_PORT
      USERSMS_HOST: $USERSMS_HOST
      USERSMS_PORT: $USERSMS_PORT
    ports:
      - $GATEWAY_PORT:$GATEWAY_PORT
    networks:
      - microservices-network

  usersms:
    platform: linux/amd64
    build:
      context: ./UsersMS
      target: prod
    hostname: $USERSMS_HOST
    restart: unless-stopped
    environment:
      PORT: $USERSMS_PORT
    networks:
      - microservices-network

networks:
  microservices-network:
    driver: bridge